# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Drakula2k
email: drakula2k@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yet another Ruby developer's blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://drakula2k.com" # the base hostname & protocol for your site
twitter_username: Drakula2k
github_username:  Drakula2k

# Build settings
markdown: kramdown
